### PR TITLE
clean up of render artifact near upper right corner of 3d cube + Player Controls Option

### PR DESCRIPTION
**Pull request by mgonzales71**
update: See below for 2nd part of this PR.. Player Controls (skin option)

hard to notice over lighter backgrounds but very noticeable on the darker ones...

### CODE REVIEW

**Comment by mgonzales71** [comment]
Skin Setting to Enable Player Controls when not in full screen playback
or audio visualization

uses it's own set of OSD buttons (if you don't like maybe Simograndi can
provide some similar to existing OSD)

see screenshots for examples of video and audio playback

should support live tv but unable to test that.

did not exclude this from "classic" - feel free to change if that is
desired.

(also supports mouse/touch for window close)

Also - I haven't yet selected which color theme options should apply to the text... suggestions?
OSD maybe?

screeenshots.....

**Comment by mgonzales71** [comment]
I have found one issue - but I can't seem to figure out how to solve it.

I was hoping <aspectratio>keep or scale</aspectratio> would solve this but it doesn't

you know how to solve this properly?

some tv shows (and some live streams via add-ons) can have issues:

**Comment by mgonzales71** [comment]
Think I figured it out.  tried several video sources and they seem to now stay in the box but adjusted for their ratio/scale.

if you know a better way i would love to learn the secrets from the master ;-) - thanks!!! 

Mario

**Comment by mgonzales71** [comment]
test results from numerous video sources last commit....

fotorcreated

**Comment by marcelveldt** [comment]
Hi Mario... What's the benefit of this having in the center of your screen?
Did you also notice that the upper bar also incldes some player controls when touchmode is enabled ?

I like the idea of this but I'm not entirely sure if it's usable for users if it's positioned in the center of the screen, it renders the screen's content unusable... Or am I missing something ?

**Comment by mgonzales71** [comment]
I don't use mouse or touch controls on my PC - keyboard only so I didn't notice it.
but if you don't think it's useful then you don't have to include it.

I just figured it might be useful in addition to the now playing in background/upper right corner/etc 

the second part to this was to maybe add "quick nav" feature for when nothing was playing (instead of the player controls).

**Comment by mgonzales71** [comment]
oh forgot to answer why the middle of the screen - because the use of the controls are only meant to be momentary and it made sense to make them the center of the screen.

did you test out the mod by chance to see how it works?

pressing M on the keyboard brings the controls up.

**Comment by mgonzales71** [comment]
here is a zip of the changes if you wanted to try them out 
https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!4653&parId=599DA6BD82779E65!4605&authkey=!AKzUYUGH4kazD6Y&ithint=file%2czip

in this zip - I actually have favorites pop up if nothing in playing (as a test for a quicknav like feature)  the end goal would be a menu like the power menu but be a 6x6 icon grid where you could use the skin shortcuts editor to populate with things you wanted quick access to.

maybe its all redundant - so if it is not a good fit you can nix it - don't feel bad I do these little projects to help me learn anyway :)

**Comment by marcelveldt** [comment]
Ah, now it makes sense. You have to enter M to open it..
In that case I'll include it even without the option, thanks for explaining.

I will merge your request and review the code.

Thanks a lot for the contribution once again!

**Comment by mgonzales71** [comment]
you're welcome.  

I am going to make some updates to this mod now that you are ok with it..

Question: 
should the panel color follow general or OSD?  (that will tell me which text colors to follow as well)
or should I just leave it as is?  

also - can get icons from simograndi to match existing if you like as well - he already offered to do them if requested.

finally - if you think it's a good idea to have it as a feature could you give me a little tip on how I would do the quick nav side of this?

thinking was something akin to the powermenu but displayed as a 6 x 6 icon grid at center screen when pressing M and nothing is playing - alot of skins have this a customizable jump list or quick nav utilizing the playercontrols.xml when nothing is playing (the reasoning for expanding beyond just playercontrols)

the powermenu stuff appears to utilize skin shortcuts for alot of it.

**Comment by mgonzales71** [comment]
submitted PR to fix conflict with 2 files:
https://github.com/marcelveldt/xbmc.skin.titan/pull/95

**Pull request merged**
