### PR TITLE
nextup notification skin support added

### PR DESCRIPTION
**Pull request by mgonzales71**
nextup notification skin support added

https://github.com/im85288/service.nextup.notification

http://forum.kodi.tv/showthread.php?tid=228435

### CODE REVIEW

**Comment by mgonzales71** [comment]
***NextUP Notification Screenshot***



***Still Watching? Notification Screenshot***

**Comment by marcelveldt** [comment]
Thanks for doing this! It was still on my TODO list. One question however... Why isn't it positioned and styled exactly like the OSD ?
Or does it show together with the OSD maybe (on purpose) ?

**Comment by mgonzales71** [comment]
You're welcome Marcel :-)

Regarding location displayed...

The script has a default location of the lower right (which I didn't like) and the other skin examples I have seen had placed the dialog either huge and full screen (didn't like that either) or placed it offset to one side or the other...

I tried a few locations but keep liking this spot the most.. Also it made sense to show it on the screen in a place so as to not obscure the other controls or Info displayed.  

It's easily moved if you don't like it there.  

Wherever it's displayed it should be a location above the OSD and below the header / Info OSD don't you think?

As always glad to help :-)

**Comment by mgonzales71** [comment]
oh btw - if you haven't yet read about or used this service... it displays a dialog telling the user what's next up to play (if anything) with a countdown the last 60 seconds of a show *(for example, you can change in settings) - if you let the timer run down it will auto play the next episode.

you can set it to check after for example 3 episodes auto played - asking "are you are still there?"

if you don't confirm that dialog - auto playback stops.

**Pull request merged**
