### PR TITLE
busy spinners

### PR DESCRIPTION
**Pull request by mgonzales71**
busy spinners

### CODE REVIEW

**Comment by marcelveldt** [comment]
merged. Thanks!

**Comment by mgonzales71** [comment]
cool - let me grab a new copy and check it out!  :grinning: 

did you see my comment on dim color settings option?

**Comment by marcelveldt** [comment]
Yep, I saw that. Changed it to a more dark color. Not yet needed to make it configurable yet. It is meant to dim the screen for specific dialogs so the dialog will be well visible. I will leave it like this for now

**Comment by mgonzales71** [comment]
Communist!!  LOL :smiling_imp: hahaha

**Comment by marcelveldt** [comment]
hahaha, well if people really start complaining about it I will add it in ;-)

**Pull request merged**
