### PR TITLE
more fancy spinners

### PR DESCRIPTION
**Pull request by mgonzales71**
check out 3d rings - very cool spinner!

### CODE REVIEW

**Comment by mgonzales71** [comment]
also added a few icons to spinner selection dialog:
animated-gif-icon
animated-spinner-folder-icon
no-spinner-icon

**Comment by mgonzales71** [comment]
ok - think I am all spinner'ed out for now (unless you have a request for a type, etc you want to see)

its a bit of work for the multi-image ones but I had fun doing it.

I gave up on the animated gif's - they don't have the quality that the png's have (since there transparency is either on or off)

**Comment by mgonzales71** [comment]
forgot the kodi logo - oops! - fixed :)

kodi-logo-s

**Comment by marcelveldt** [comment]
Haha Mario, you're on a spin!

Great stuff, merged :-)

**Comment by mgonzales71** [comment]
one more and fix coming up in a new PR any second now... :grinning:

**Pull request merged**
