### PR TITLE
Studio Logos

### PR DESCRIPTION
**Pull request by taurus35**
Marcel,
Not sure if I've done this right but here (hopefully) are 90 studio icons I had that are not in your folder. Some of them aren't the best & could do with some work.

### CODE REVIEW

**Comment by marcelveldt** [comment]
Thanks, great work. I will do a quick review and add them to the skin tomorrow.
Regards,

Marcel

**Comment by taurus35** [comment]
Marcel,
Have just added the missing Genre icons we spoke of before. I had to guess the font & got as close as I could, unless you know what it is or can find out. If there are any other you would like done just let me know....as long as you are happy with them of course.
Cheers.

**Comment by marcelveldt** [comment]
I've added your studio logos and genre icons to the skin. 
I will try to push another skin update out tonight.

Thanks a lot for your contribution!

Cheers,
Marcel

**Comment by taurus35** [comment]
Hi Marcel,

 

No problem, glad they were OK.

 

Cheers,

 

Kevin

**Pull request merged**
