### PR TITLE
update fonts & colors for confluence compatibility

### PR DESCRIPTION
**Pull request by mgonzales71**
update fonts & colors for confluence compatibility

old Bold and Regular TTF's were based on Ubuntu TTF
old Light TTF was based on older Roboto TTF.

Roboto was designed to replace older Ubuntu fonts - they have very
similar profiles so should not affect skin look and feel.

Roboto was developed for a more "modern" look and feel in Android 4 and
was later cleaned up and improved for Android 5 (Material Design)

Updated all fonts to latest version of the Roboto TTF's from Google
download site.

### CODE REVIEW

**Comment by mgonzales71** [comment]
screenshot to show the changes in this PR bring much better compatibility when an addon uses skin resources based on confluence skin colors and fonts.

screenshot001

**Comment by marcelveldt** [comment]
Thanks again Mario!

**Comment by marcelveldt** [comment]
Mario,
I reverted the fonts change/update because it didn't look right. It was a whole diffferent font.
A lot of text was way to big or just didn't look well. For now I placed the old font files back.

**Comment by mgonzales71** [comment]
ok - i thought it looked a little better but thats your call ;-)
did you keep the other changes?

**Pull request merged**
