### PR TITLE
Support for new favouriteepisodes query type in service.library.data.pro...

### PR DESCRIPTION
**Pull request by SumnerH**
...vider

Hey Marcel,

Here's the branch to support the new favourites code in service.library.data.provider.  Essentially if you have any favourite TV shows, then it'll show the oldest unwatched episode from each of them.

This is my first time tweaking a kodi/xbmc skin so let me know if I bungled anything.  I piggybacked on an already existing "Favourite Episodes" translation string rather than duplicating it, I think that's okay?

Thanks for your time,

Sumner

### CODE REVIEW

**Comment by SumnerH** [comment]
Longer explanation of the library changes is in that PR over here: https://github.com/BigNoid/service.library.data.provider/pull/27

**Comment by marcelveldt** [comment]
Hi Sumner,
I'll merge the changes. Thanks!

Do you have any idea when the PR in the library-service will be available ?

Rgerads,

Marcel

**Comment by SumnerH** [comment]
All I know is BigNoid's comment from that PR, he'd already merged it into his repo and said 2 days ago:
 "I'll have to update it for the official repo. That can take a few days. I'll submit a PR today."

**Comment by marcelveldt** [comment]
just a quick note that I just pushed out a new beta update of the skin with this fix included. Will push to stable repo as soon as the change from BigNoid is updated on the repo so will be end of the week or so.

**Comment by SumnerH** [comment]
Awesome, thanks!

**Pull request merged**
