### PR TITLE
trakt custom skin files renamed + solid background, larger & themed playercontrols

### PR DESCRIPTION
**Pull request by mgonzales71**
make panel background solid / non-transparent for easier reading at
distance

### CODE REVIEW

**Comment by mgonzales71** [comment]
I was gonna ask - do you really want the dialogoverlayextra?
if the background is solid/non-transparent it is alot easier to read plus you can read the header much easier also which has the now playing info title/time for playing video's, etc 
just a thought.

I went ahead and re-did the PR with at least the one change you didn't get the 100% for the panel.

**Comment by mgonzales71** [comment]
2nd commit - latest update to trakt script has renamed it's custom skin xml files -
this address that

**Comment by mgonzales71** [comment]
playercontrols larger dialog, solid background, themed for OSD colors in skin.




think I like the buttons for this dialog as is - you ok with them?

**Comment by mgonzales71** [comment]
suggest a modification of the dialog dimming to allow clear view of the
now playing header info.




(I was playing around with various color for OSD panel color btw in screenshots)

**Comment by marcelveldt** [comment]
Hey Mario, all is okay with me except for the change about the dialogoverlay. Just use that include and not copy the code in another window. This will drive me crazy once I want to make a modification at higher level.

No code should be duplicated. If it's used in multiple places then it should be an include at all times.

Just like the way a proper CSS file should be built when building a website.

i get your point of wanting the "now playin"g bar" visible when the playercontrols are on screen. This can be easy fixed by including the Nowplaying include in the playercontrols. Just below the include of dialogoverlayextra (which is the screen dim actually), place another include for the nowplaying. take a look at the home window for example how that looks like...

BTW: my overall opinion is that this is a nice addition. Thanks!!

**Comment by mgonzales71** [comment]
regarding the duplicate code vs doing an include - wasn't sure if you wanted an include for a unique case.

I am going to fix here in a second so it is clean/ready for you.

**Comment by mgonzales71** [comment]
should be all good now :smile:

**Comment by marcelveldt** [comment]
wiehoe! thanks!

**Comment by mgonzales71** [comment]
finally hehe - now maybe you can point me towards how to do the quicknav thing?
i know it uses skin shortcuts and I have read over the code and it's not so easy to know what I can and can't do, etc

actually it may be something best left to an expert / or later time  LOL

**Comment by marcelveldt** [comment]
Yeah, I;ll check on it later on. First I try to get the current release stable

**Pull request merged**
