### PR TITLE
3 new/updated themes

### PR DESCRIPTION
**Pull request by mgonzales71**
3 new/updated themes

### CODE REVIEW

**Comment by mgonzales71** [comment]
Ok - _finally_ updated themes with all new options enabled in recent commits.
:grinning:

**Comment by mgonzales71** [comment]
Also adding Additional Background Overlays

**Comment by mgonzales71** [comment]
found the system info widget code - updated fanart and adjusted code for updated images

here is a screenshot - hope you like...

screenshot000

**Comment by marcelveldt** [comment]
Wiehoo! Great work, thanks!

**Pull request merged**
