### PR TITLE
New DialogBusy Animated Spinner textures

### PR DESCRIPTION
**Pull request by mgonzales71**
The individual frames of the busy spinner:

hard to see in action due to color and transparency - but here is an animated png and gifs of the spinner as well:

### CODE REVIEW

**Comment by mgonzales71** [comment]
update...

expanded earlier work on Dialog Busy animation:

added support for custom busy animation and color

support for setting dialog busy animation to an animated gif or multi
image folder of gif/png image files.

support added to define color diffuse of busy, progress and extended
progress animation

added a couple animated gif and multi image folders to extras

You can find lots of animated GIFs at http://preloaders.net

also if you use the tools at that site to make an APNG (Animated PNG file, which Kodi does not yet support :disappointed:)

but if you do download an APG - you can use this windows program to explode it into individual image files (you can discard the txt files it makes)

http://apngdis.sourceforge.net/

**Comment by mgonzales71** [comment]
also added back original animation to extras folder :smile:

**Comment by mgonzales71** [comment]
is there a way to have a folder or image select dialog start in a certain place?
was thinking it would be nice to have the respective dialogs start in the proper location in the extras folder.

**Comment by mgonzales71** [comment]
screenshot000

**Comment by marcelveldt** [comment]
Hey Mario, nice suggestion about the loading indicator but I won't implement it as you suggested. Want to make it a bit more fancier ;-)

What I want to do is create an extra folder in the skin's extras folder where the busy indicators are stored and present the user with a dialog to choose from. Does that sound good to you ?

**Comment by mgonzales71** [comment]
yea - I figured you would more likely lean towards something like that but could you also allow the user to over-ride it somehow and use an animated GIF or folder of images (gif or png's) of their own?

did you try out what I have done so far? :)

hopefully you also keep the color setting for the indicator as well - which allows not only custom colors but if the user wants to use a full color animation they can select NONE and not have it tinted at all.

feel free to make it better and fancier -  better is always... well, better! LOL

**Comment by mgonzales71** [comment]
an multi-image set for testing.  *(I used color set to 77white for this one)

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!4626&parId=599DA6BD82779E65!4605&authkey=!AFYLMBSHEaah7_E&ithint=file%2czip

just occurred to me that the color setting for busy may not be the color you want to use for progress or extended progress - maybe keep the seperate?

**Comment by marcelveldt** [comment]
Hey Mario,

please check out the latest version from Git.

I have added in the settings for the busy dialog, you can find them in the general skin settings section.

It will process any gif images in the extras\busy_spinners folder. Also it will process any subfolders of that for multiimage animations.

For now I included some gif spinners from the artctic zephyt skin but they're pretty lowres.

If you want could you look up some good looking copyright-free spinner animations and do a PR for that ?

**Comment by mgonzales71** [comment]
ok - let me go grab it and check it out.

did you not include a way to allow the user to use their own image(s)?  - the extras folder gets overwritten if the skin gets updated 

if you want to close this PR - can create an Issue to discuss this FR.

**Comment by marcelveldt** [comment]
Check out the latest Git and see... It will allow you to select from predefined the user can select his own gif or folder for the animation...

I meant with the extras folder is that if you want you can provide me some spinners to put in there ;-)

Yes, please close this one and do a new PR if you have some good spinners :-)

**Comment by mgonzales71** [comment]
closing this PR - moving discussion to https://github.com/marcelveldt/xbmc.skin.titan/issues/84

**Pull request closed without merging**
