### PR TITLE
First Steps in Font Clean-up/Updated Font testing

### PR DESCRIPTION
**Pull request by mgonzales71**
Found Double fontname statements with 2 different sizes

Reg28 --> 32

Reg34 --> 40

so I did a search for all files with <font>Reg28</font> and updated them
to <font>Reg32</font>
and the same for Reg34 to Reg40

I cleaned up the orig fontsets and removed the duplicates

Also created 3 new fontsets: default-new, Arial-new and Large-new

I cleaned up/added the following groups of fontnames: Reg, Light, Bold,
BigBold (Bolded Bold) and Black

each group should now all have the same <size> elements available

I suggest if you add a new size like Reg## you add that to all groupings
of fontnames.

they use 4 new fonts based on TTF Roboto... Regular, Light, Bold and
Black (all with a -new added to filenames)

the orignal TTF font files are untouched.

Go into appearance settings and change to a fontset-NEW and test out the
changes

if after testing and approval we can remove the orginal fontsets and
renamed the -NEW to take their place along with the TTF's

### CODE REVIEW

**Comment by mgonzales71** [comment]
I know this is a huge update / PR --- ** other then the removal of the the duplicate name/sizes and the update of the files that used the sizes their should be no impact to normal users unless they change fontsets.** (fingers crossed) :-)

**Comment by marcelveldt** [comment]
Hi Mario, thanks for your work on this!
I will merge it in and test out and let you know.

**Comment by marcelveldt** [comment]
I'm currently testing out the font changes but like last time something just isn't right... The font is wrong, it almost looks like Arial (just a plain boring font), not the rounded touch the old font has. And besides that, all texts are way to big. For example the RSS freed or all settings buttons etc.

**Comment by marcelveldt** [comment]
Can you confirm that in your setup the font size is also too big when using the new font ?

**Comment by mgonzales71** [comment]
Here is a comparison 

default



default-new



both images with 50% transparency overlay on top of each other

over

**Comment by marcelveldt** [comment]
Strange! On my setup the fonmt is HUGE and it looks like Arial. In your screenshots it looks fine.

**Comment by mgonzales71** [comment]
Really?! - that is odd!  Hmmm - and you have all the fonts installed?

Just for another look at roboto vs ubuntu

here is another comparison... roboto, ubuntu and then an overlay of both at 50%



overlay

**Comment by mgonzales71** [comment]
if anything ubuntu is a little less compact but is not as clean as roboto.

**Comment by marcelveldt** [comment]
yep, fonts are in the fonts folder...
strange...

**Comment by mgonzales71** [comment]
other then your RSS - do you see anything else strange?

I wonder why you are not seeing the same as I am?

what platform are you using this on?

just for apples to apples

try installing the same zips I did?

https://github.com/mgonzales71/xbmc.skin.titan/tree/master/test%20build

**Comment by marcelveldt** [comment]
I'm on Windows 8.1 x64...

after reboot the RSS feed now seems tro be fine, it's just a whole lot of other sections that have wrong font size, for example:

- title on widget
- all textboxes (movie plot)
- settings options
- etc

screenshot000
screenshot001

**Comment by marcelveldt** [comment]
screenshot002

**Comment by mgonzales71** [comment]
You really don't like the new look?  it's cleaner to me but the change is not my call. :-)

could always just make a new fontset by re-naming default-new to something like default-alternate and calling at a day?

I would at least copy default-new to default and rename all the fonts removing the -new from TTF names so you have all the new sizes and font groups reg, light, bold and bigbold  (and black)*

*if ubuntu has a "black" variant

do you want me to clean it back up and just go with an -alternate?

If I can't find an ubuntu black I will kill those off as well.

**Comment by mgonzales71** [comment]
oh there is a roboto-medium now that I think about it too...

**Comment by marcelveldt** [comment]
It's not that I don't like it.. It's that the fontsize is WAY too big. It should be okay looking at your screenshots so something is wrong.

**Comment by mgonzales71** [comment]
try installing my zip's from link above.

for comparison see my screenshot of settings *notice version numbers are different...

**Comment by mgonzales71** [comment]
Just can't understand why they look different.

I am on WIn 8.1 x64 - Helix 14.2 - sounds like same systems.

**Comment by marcelveldt** [comment]
I have the git source checked out on my system, that's why the version number differs...
Basically it's the stable version ID and version with the latest code. That way I'm sure that I have all stuff exactly the same in Git and on my build machine.

Will try your version to see if there's any difference

**Comment by marcelveldt** [comment]
just looking at your screenshot.. Looks like the fontsize it too big in there too...

**Comment by mgonzales71** [comment]
still very odd you are not seeing the same fonts and sizes I am.
let me know if installing the zips resolved anything or not.

**Comment by marcelveldt** [comment]
Aha! Just discovered that it is even too big when using the default fontset so it must have something to do with the change in the font.xml file itself.

Also same issue when using your test build

**Comment by mgonzales71** [comment]
but - I am using the same fonts.xml and not seeing any issues

**Comment by marcelveldt** [comment]
Yes, that is the issue... I suspect you did a find replace on that reg28 and reg34 case ?

**Comment by mgonzales71** [comment]
and when I change fontsets the fonts change

the find and replace I did was in the xml files that used those and updated them to the larger size since you had two declarations for the same font name

**Comment by mgonzales71** [comment]
should I have picked the smaller size or the larger size?
It was late - did I leave duplicates in or something?
still odd that installing the zip on my system does not show the same as yours,.

**Comment by marcelveldt** [comment]
It should be the smaller one.. Apparently if there's a duplicate font entry, Kodi will pick the first one it finds.
Now all fonts that are skinned as 28 are now 32 so that's a whole lot bigger

**Comment by mgonzales71** [comment]
see - I thought you did not want to edit all the files with the new fontname and just upped the size of 
Reg28 --> Reg32
and
Reg34 --> Reg40

that is why I updated all references to them with the larger Reg## - should have asked which you had intended lol

so - if we revert the changes of Reg28 and Reg34 do things look better to you then?

**Comment by marcelveldt** [comment]
Im currently testing that...

**Comment by marcelveldt** [comment]
OK, please check out latest git... I think I now have fixed the fontsize but I didn't check every single area of the skin.

**Comment by marcelveldt** [comment]
changed the font.xml file so that the new font is now default. Left the old font in there as "classic". 
Once pushed to the beta repo we just let users give it a shot and see if they like it. If they don't like it they can even revert to classic.

**Comment by mgonzales71** [comment]
I am installing new build now... so did the oddness fix itself once you went to the lower font size?
sorry about that - I just made the wrong assumption on the reason for the duplicates...
do you know how/why they were there??

**Comment by mgonzales71** [comment]
also - give the new bigbold and black fontnames a try next time you need something like a title or header and see what you think vs the reg or bold fontnames,

**Comment by marcelveldt** [comment]
I guess I just made a mistake with that duplicate font names and never noticed it. No rpoblem, it's cleanup up now :-)

Will give the new black/bold ones a try soon

**Comment by mgonzales71** [comment]
cool - sorry didn't mean for my changes to cause so much drama! hehe

lets now see what the masses think of the changes and if my idea was a good one or not! ;-)

**Comment by marcelveldt** [comment]
haha lol, no fuss at all, at least now the font code has been cleaned up ;-)

While testing I spotted a few errors with the text in textbox controls not fit correctly. Changed it wherever I saw it. Please feel free to correct any more errors when you spot them. The new font is a bit higher so sometimes the text doesn't fix very well in the textbox. Fix is just increasing the textbox height with 4 ot 5 pixels..

**Comment by mgonzales71** [comment]
ok - will work on that this evening when I have time to look at things more in depth.

speaking of text boxes and buttons - I noticed some of them (ie subtitle dialog, weather, etc) do not use the same text color / shadow color for focused, unfocused, etc as the rest of the skin.

I prob should start to make a list of those while I am looking around so we can get consistency with the rest of the skin.

**Comment by mgonzales71** [comment]
Hey Marcel,

I got to thinking last night and again today - I should have had you look here:

https://www.google.com/fonts

lots of freely available fonts - and some nice suggested font pairings as well

The more I think about it - two or more fonts paired for use in the skin at the same time is better then just one.

take a peek at that link and see what jumps out at you.

Also - in the font sets - I think the font names should be like the following (adding new ones as you create new text elements of the skin)...

Header
SubHeader
OSDTitle
OSDSubTitle
Footer
SubFooter
Title
RSS
Button
ButtonBold
BigButton
ListHeader
ListItem
HomeTile
HomeTileSubMenu
etc
etc
etc

**Comment by marcelveldt** [comment]
Yeah, you're right about the font definitions. It was like this when I took over the Original titan theme and I never changed it. Will be a hell of a job to change it...

**Comment by mgonzales71** [comment]
yeah - it would be a pain... I need to get some unix cmd line tools installed on my windows box again - I am curious how many unique font sizes are actually in use by the skin as a whole.

if you ever decide to start up a new "son" of titan skin or something don't forget LOL :smile:

**Pull request merged**
